import Head from 'next/head'
import Script from 'next/script'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet"/>
      </Head>

      <>
        {/*=============== HEADER ===============*/}
        <header className="profile container">
          {/* Theme button */}
          <i className="ri-moon-line change-theme" id="theme-button" />
          <div className="profile__container grid">
            <div className="profile__data">
              <div className="profile__border">
                <div className="profile__perfil">
                  {/* Insert your image, according to the example size of the portfolio */}
                  <img src="/img/me .png" alt="" />
                </div>
              </div>
              <h2 className="profile__name">Adrian Solomon</h2>
              <h3 className="profile__profession">Web developer</h3>
              <ul className="profile__social">
                <a
                  href="https://www.instagram.com/adrian_r.solomon/"
                  className="profile__social-link"
                >
                  <i className="ri-instagram-line" />
                </a>
                <a
                  href="https://www.linkedin.com/in/adrian-solomon-8b3624219/"
                  className="profile__social-link"
                >
                  <i className="ri-linkedin-box-line" />
                </a>
                <a
                  href="https://github.com/AdrianRSolomon"
                  className="profile__social-link"
                >
                  <i className="ri-github-line" />
                </a>
              </ul>
            </div>
            <div className="profile__info grid">
              <div className="profile__info-group">
                <h3 className="profile__info-number">2</h3>
                <p className="profile__info-description">
                  Years of <br /> work
                </p>
              </div>
              <div className="profile__info-group">
                <h3 className="profile__info-number">3</h3>
                <p className="profile__info-description">
                  Completed <br /> projects
                </p>
              </div>
              <div className="profile__info-group">
                <h3 className="profile__info-number">1</h3>
                <p className="profile__info-description">
                  Satisfied <br /> customers
                </p>
              </div>
            </div>
            <div className="profile__buttons">
              {/* Insert your CV */}
              <a download="" href="https://drive.google.com/file/d/1BGKlFMvWzju69dHOHH-Cp2LDuZUXHPYh/view?usp=sharing" className="button">
                Download CV <i className="ri-download-line" />
              </a>
              <div className="profile__buttons-small">
                {/* Insert a real number plus country code */}
                <a
                  href="https://api.whatsapp.com/send?phone=51123456789&text=Hello, more information!"
                  className="button button__small button__gray"
                >
                  <i className="ri-whatsapp-line" />
                </a>
                {/* Insert your brand name or profile */}
                <a
                  href="https://m.me/bedimcode"
                  className="button button__small button__gray"
                >
                  <i className="ri-messenger-line" />
                </a>
              </div>
            </div>
          </div>
        </header>
        {/*=============== MAIN ===============*/}
        <main className="main">
          <section className="filters container">
            {/*=============== FILTERS TABS ===============*/}
            <ul className="filters__content">
              <button
                className="filters__button filter-tab-active"
                data-target="#projects"
              >
                Projects
              </button>
              <button className="filters__button" data-target="#skills">
                Skills
              </button>
            </ul>
            <div className="filters__sections">
              {/*=============== PROJECTS ===============*/}
              <div
                className="projects__content grid filters__active"
                data-content=""
                id="projects"
              >
                <article className="projects__card">
                  {/* Insert your image in a rectangular format (Ex: 600 x 400, 1000 x 800, 1200 x 1000, etc) */}
                  <img
                    src="/img/a1tech.png"
                    alt=""
                    className="projects__img"
                  />
                  <div className="projects__modal">
                    <div>
                      <span className="projects__subtitle">Web</span>
                      <h3 className="projects__title">A1 Technologist</h3>
                      <a href="https://a1technologist.vercel.app/" className="projects__button button button__small">
                        <i className="ri-link" />
                      </a>
                    </div>
                  </div>
                </article>
                <article className="projects__card">
                  <img
                    src="/img/matchrealtor.png"
                    alt=""
                    className="projects__img"
                  />
                  <div className="projects__modal">
                    <div>
                      <span className="projects__subtitle">Match Realtor</span>
                      <h3 className="projects__title">Portfolio website</h3>
                      <a href="#" className="projects__button button button__small">
                        <i className="ri-link" />
                      </a>
                    </div>
                  </div>
                </article>
                <article className="projects__card">
                  <img
                    src="/img/adrianportfolio.png"
                    alt=""
                    className="projects__img"
                  />
                  <div className="projects__modal">
                    <div>
                      <span className="projects__subtitle">Movil</span>
                      <h3 className="projects__title">Fast food app</h3>
                      <a href="#" className="projects__button button button__small">
                        <i className="ri-link" />
                      </a>
                    </div>
                  </div>
                </article>
              </div>
              {/*=============== SKILLS ===============*/}
              <div className="skills__content grid" data-content="" id="skills">
                <div className="skills__area">
                  <h3 className="skills__title">Frontend Developer</h3>
                  <div className="skills__box">
                    <div className="skills__group">
                      <div className="skills__data">
                        <i className="ri-checkbox-circle-line" />
                        <div>
                          <h3 className="skills__name">HTML</h3>
                          <span className="skills__level">Basic</span>
                        </div>
                      </div>
                      <div className="skills__data">
                        <i className="ri-checkbox-circle-line" />
                        <div>
                          <h3 className="skills__name">CSS</h3>
                          <span className="skills__level">Advanced</span>
                        </div>
                      </div>
                      <div className="skills__data">
                        <i className="ri-checkbox-circle-line" />
                        <div>
                          <h3 className="skills__name">JavaScript</h3>
                          <span className="skills__level">Intermediate</span>
                        </div>
                      </div>
                    </div>
                    <div className="skills__group">
                      <div className="skills__data">
                        <i className="ri-checkbox-circle-line" />
                        <div>
                          <h3 className="skills__name">React</h3>
                          <span className="skills__level">Intermediate</span>
                        </div>
                      </div>
                      <div className="skills__data">
                        <i className="ri-checkbox-circle-line" />
                        <div>
                          <h3 className="skills__name">Bootstrap</h3>
                          <span className="skills__level">Intermediate</span>
                        </div>
                      </div>
                      <div className="skills__data">
                        <i className="ri-checkbox-circle-line" />
                        <div>
                          <h3 className="skills__name">Git</h3>
                          <span className="skills__level">Intermediate</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="skills__area">
                  <h3 className="skills__title">Backend Developer</h3>
                  <div className="skills__box">
                    <div className="skills__group">
                      <div className="skills__data">
                        <i className="ri-checkbox-circle-line" />
                        <div>
                          <h3 className="skills__name">PHP</h3>
                          <span className="skills__level">Basic</span>
                        </div>
                      </div>
                      <div className="skills__data">
                        <i className="ri-checkbox-circle-line" />
                        <div>
                          <h3 className="skills__name">MySQL</h3>
                          <span className="skills__level">Basic</span>
                        </div>
                      </div>
                      <div className="skills__data">
                        <i className="ri-checkbox-circle-line" />
                        <div>
                          <h3 className="skills__name">Node Js</h3>
                          <span className="skills__level">Intermediate</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </main>
        {/*=============== FOOTER ===============*/}
        <footer className="footer container">
          <span className="footer__copy">© Adrian Solomon. All rigths reserved</span>
        </footer>

      {/*=============== SCROLLREVEAL ===============*/}
      <Script type="text/javascript" src="/scrollreveal.min.js" strategy="lazyOnload"></Script>

      {/*=============== MAIN JS ===============*/}
      <Script type="text/javascript" src="/main.js" strategy="lazyOnload"></Script>
      </> 
    </>
  )
}
